### ISSUE TITLE
Strange meta crash saving doc.

### ISSUE THREAD

**Issue by EliseyP** [eea/odfpy#105]
If we have some strange meta data in odt, f.e.: (it's really file on my archive, instead '\n' usual newline) 
--- meta.xml: -----------------------  
<office:meta>     
\n        
\n         
\n       
\n          
\n          
\n        
  <dc:title>+</dc:title>
\n  
\n  
\n  
\n  
\n  
\n  
  <meta:initial-creator>Serafim</meta:initial-creator>
\n
... and so one
--- meta.xml -----------------------

**OpenDocument.__replaceGenerator()** /in opendocument.py/ crash with AttributeError.

I put code to try/except, and it work correctly.
strings 575-578:
```
def __replaceGenerator(self):
        try:
            for m in self.meta.childNodes[:]:
                if m.qname == (METANS, u'generator'):
                    self.meta.removeChild(m)
            self.meta.addElement(meta.Generator(text=TOOLSVERSION))
        except AttributeError:
            pass
```
in childNodes we have excess Text elements: '\n\n\n\n\n\n' and try\exept let ignore this.

**Comment by sorenroug** [comment]
The 'except' clause doesn't replace the generator element if there is a text node in the XML file. I have committed another fix.
