### ISSUE TITLE
KeyError with some ods files

### ISSUE THREAD

**Issue by fisxoj** [eea/odfpy#16]
I found this report from two years ago, too:
https://joinup.ec.europa.eu/software/odfpy/issue/mimetype-error-when-working-ods-files-google-drive

I don't know if the file that caused my error is downloaded from google drive or not, but it's the same error.

I can hack around it in my code, but it would be nice to have it fixed, especially since it seems like these files are still readable.

```
   mimetype = z.read('mimetype')
File '/usr/lib/python2.7/zipfile.py', line 869 in read
  return self.open(name, "r", pwd).read()
File '/usr/lib/python2.7/zipfile.py', line 892 in open
  zinfo = self.getinfo(name)
File '/usr/lib/python2.7/zipfile.py', line 859 in getinfo
  'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'mimetype' in the archive"
```

**Comment by fisxoj** [comment]
Looking into this further, it may be that the latest version of this library isn't in PyPI and this bug is already fixed...

**Comment by bufke** [comment]
This project doesn't really have anyone maintaining it - if you'd like to help I can give you pypi access. I'm the developer of this - I just put it on pypi when someone removed it so that packages that depend on it would build.

**Comment by sorenroug** [comment]
We're actually at version 1.3 in the source but I lost access to upload to pypi years ago. If someone will let the account 'roug' have write permission, I can build the newest version and upload it.

**Comment by fisxoj** [comment]
@bufke: If @sorenroug is willing to handle putting it on pypi, I think that's best.  I don't have experience with the source of this library or putting things on pypi. Just having the latest version would be nice, even if the library isn't being actively improved at this point.

**Comment by bufke** [comment]
@sorenroug awesome - added you.

**Comment by sorenroug** [comment]
https://pypi.python.org/pypi/odfpy/1.3.0
