### ISSUE TITLE
loading ods with Chinese characters fails with Python 2.7

### ISSUE THREAD

**Issue by MartinBorg** [eea/odfpy#19]
it works however with Python 3.4

see the two attachments test01.py and test1.ods at this Debian bug report:

https://bugs.debian.org/783789

it used to work before the Python 3 changes

**Comment by MartinBorg** [comment]
This helps, but maybe it is not the correct fix:
```
--- a/odf/attrconverters.py
+++ b/odf/attrconverters.py
@@ -103,7 +103,7 @@
 def __save_prefix(attribute, arg, element):
     prefix = arg.split(':',1)[0]
     if prefix == arg:
-        return str(arg)
+        return arg
     namespace = element.get_knownns(prefix)
     if namespace is None:
         #raise ValueError( "'%s' is an unknown prefix" % str(prefix))
```

**Comment by fisxoj** [comment]
I'm encountering this as well.  Was there a reason to cast the return value to a string instead of unicode? (https://github.com/eea/odfpy/commit/3f9eeff57943b98da22ca47219566164f4013268#diff-752a348151632fef555f0894ed7fffeeL104)

**Comment by markplindsay** [comment]
@fisxoj it looks like this WAS fixed in https://github.com/eea/odfpy/commit/d6d37d0f817f8b2dc41a02dc13d2c15ac3336e0b, but it hasn't made it into PyPI yet. 

PyPI has 1.3.1 (2015-07-18) and the fix was committed 2015-08-01.

**Comment by fisxoj** [comment]
@sorenroug It looks like you were our savior [last time around](https://github.com/eea/odfpy/issues/16#issuecomment-115731953).  Do you think a new release to PyPi might be possible?

**Comment by sorenroug** [comment]
Yes, the fix was committed in August, but it didn't work on both Python 2 and 3. I've done some investigation and closed the issue. There is a new release on PyPi.

**Comment by fisxoj** [comment]
Thanks, @sorenroug!
