### ISSUE TITLE
please do not set HTML_TIMESTAMP = YES in config.dox

### ISSUE THREAD

**Issue by MartinBorg** [eea/odfpy#20]
Recently, doxygen changed the default of `HTML_TIMESTAMP` from `YES` to `NO`. The new value is "better"™, because it allows reproducible builds, i.e. two builds of the software have identical results. Please either remove the override in `config.dox` or set `HTML_TIMESTAMP` to `NO`. Thanks!

See https://bugs.debian.org/777635, if necessary.

**Comment by sorenroug** [comment]
Done
