### ISSUE TITLE
DUPLICATE HREF GENERATED IN addPictureFrom*

### ISSUE THREAD

**Issue by rgusmero** [eea/odfpy#30]
Functions addPictureFrom* in odf.opendocument use time.time() to gemerate unique filenames. If the functions are called in a loop, this can result in duplicate names due to limited resolution of time.time() in some systems (tested on old Windows Vista PC).

A possible workaraound is the use of uuid module replacing

manifestfn = u"Pictures/%0.0f%s" % ((time.time()*10000000000), ext)

with

manifestfn = u"Pictures/%s%s" % (uuid.uuid4().hex.upper(), ext)

**Comment by sorenroug** [comment]
Implemented as suggested
