### ISSUE TITLE
Run tests automatically on TravisCI

### ISSUE THREAD

**Issue by icemac** [eea/odfpy#54]
Especially for pull requests it would be nice to run the tests automatically on [travis-ci.org](https://travis-ci.org/eea/odfpy).

This requires:

- [x] To [activate Travis-CI](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A) for this repository
- [x]  Write a [.travis.yml file](https://docs.travis-ci.com/user/languages/python/).

After completing the first step (as it requires admin privileges in this repository) I can help with the second one.

**Comment by icemac** [comment]
@sorenroug What do you think about my suggestion?

**Comment by sorenroug** [comment]
@icemac I think it is a great idea to set up continuous integration, and I'll look into the practicalities in the weekend.

**Comment by sorenroug** [comment]
I have connected Travis-CI, but the build is currently failing.

**Comment by icemac** [comment]
Fixed #56.
