### ISSUE TITLE
Bug tests, no make

### ISSUE THREAD

**Issue by ppKrauss** [eea/odfpy#60]
The README instruction is "To run the tests, `cd` into the tests directory and run make". So, 

```
root@User:/sandbox/odfpy#  cd tests/
root@User:/sandbox/odfpy/tests#  make
make: *** ... no file .. ***
```

**Comment by icemac** [comment]
Thank you for bringing this up.
See #62. Sorry that I left out to fix this documentation, too when changing the way test are run in #56.
